project_id = "psihzoyoufgqbacvvphx"

[functions.generate-activity]
verify_jwt = false

[functions.generate-code]
verify_jwt = false

[functions.github-oauth]
verify_jwt = false

[functions.github-repos]
verify_jwt = false
